services:
  web:  
    build:
      context: ./backend
    container_name: FastAPI
    environment:
      DATABASE_URL: postgresql://user:password@db/shop
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
      - frontend

  db:
    image: postgres:latest
    container_name: DBasePG
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: PG_Admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  vuejs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: VueJS
    ports:
      - "8080:80"
    networks:
      - frontend

volumes:
  fastapi_data:
  postgres_data:
  pgadmin_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge