"""Create Character_Body_Type Table

Revision ID: b5e6f9d53465
Revises: 5ac0d64eda78
Create Date: 2025-03-16 16:30:03.859825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5e6f9d53465"
down_revision: Union[str, None] = "5ac0d64eda78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_body_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_body_type")),
        sa.UniqueConstraint("type", name=op.f("uq_character_body_type_type")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_body_type")
    # ### end Alembic commands ###
