"""Create Profile Table

Revision ID: cbe6b333e052
Revises: c329a6ab26fd
Create Date: 2025-03-17 03:31:46.924874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbe6b333e052"
down_revision: Union[str, None] = "c329a6ab26fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_profile_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
    )
    op.create_index(op.f("ix_profile_user_id"), "profile", ["user_id"], unique=False)
    op.add_column(
        "profile",
        sa.Column("dh_public_key", sa.String(length=512), nullable=True, default=None),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "dh_public_key")
    op.drop_index(op.f("ix_profile_user_id"), table_name="profile")
    op.drop_table("profile")
    # ### end Alembic commands ###
