"""Create Character_Chapter Associate_Table

Revision ID: 16ac842bff65
Revises: 52975fa343b8
Create Date: 2025-03-17 01:48:01.633650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16ac842bff65"
down_revision: Union[str, None] = "52975fa343b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_chapter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.id"],
            name=op.f("fk_character_chapter_chapter_id_chapter"),
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
            name=op.f("fk_character_chapter_character_id_character"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_chapter")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_chapter")
    # ### end Alembic commands ###
