"""Create Chapter Table

Revision ID: 52983860577a
Revises: 2515c308ff2d
Create Date: 2025-03-17 01:46:26.188796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52983860577a"
down_revision: Union[str, None] = "2515c308ff2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chapter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.SMALLINT(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_id"], ["part.id"], name=op.f("fk_chapter_part_id_part")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapter")),
        sa.UniqueConstraint("number", name=op.f("uq_chapter_number")),
        sa.UniqueConstraint("title", name=op.f("uq_chapter_title")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chapter")
    # ### end Alembic commands ###
