"""Create Room Table

Revision ID: 3500093903e9
Revises: 629fc1a85c16
Create Date: 2025-05-31 00:56:25.633764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3500093903e9"
down_revision: Union[str, None] = "629fc1a85c16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("interlocutor_id", sa.Integer(), nullable=True),
        sa.Column("algorithm", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["profile.id"], name=op.f("fk_room_creator_id_profile")
        ),
        sa.ForeignKeyConstraint(
            ["interlocutor_id"],
            ["profile.id"],
            name=op.f("fk_room_interlocutor_id_profile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room")),
    )
    op.create_index(op.f("ix_room_creator_id"), "room", ["creator_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_creator_id"), table_name="room")
    op.drop_table("room")
    # ### end Alembic commands ###
