"""Create Character Table

Revision ID: ee41bb540052
Revises: b5e6f9d53465
Create Date: 2025-03-17 01:43:23.725059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee41bb540052"
down_revision: Union[str, None] = "b5e6f9d53465"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("parents", sa.String(), nullable=True),
        sa.Column("brief", sa.String(), nullable=True),
        sa.Column("favorite_phrase", sa.String(), nullable=True),
        sa.Column("body_type_id", sa.Integer(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["body_type_id"],
            ["character_body_type.id"],
            name=op.f("fk_character_body_type_id_character_body_type"),
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["character_status.id"],
            name=op.f("fk_character_status_id_character_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character")
    # ### end Alembic commands ###
