"""Create Profile_Chapter Associate_Table

Revision ID: e4a60f6a28c4
Revises: fccb9bb0e34d
Create Date: 2025-03-17 04:35:35.701317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4a60f6a28c4"
down_revision: Union[str, None] = "fccb9bb0e34d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_chapter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("is_like", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.id"],
            name=op.f("fk_profile_chapter_chapter_id_chapter"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
            name=op.f("fk_profile_chapter_profile_id_profile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_chapter")),
        sa.UniqueConstraint(
            "profile_id", "chapter_id", name="uq_profile_chapter_profile_id_chapter_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile_chapter")
    # ### end Alembic commands ###
