"""Create Request_Category Table

Revision ID: c16d8d85ee69
Revises: e4a60f6a28c4
Create Date: 2025-03-17 04:48:40.151089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c16d8d85ee69"
down_revision: Union[str, None] = "e4a60f6a28c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_category")),
        sa.UniqueConstraint("category", name=op.f("uq_request_category_category")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_category")
    # ### end Alembic commands ###
