"""Create Image_Filter Associate_Table

Revision ID: fccb9bb0e34d
Revises: e89ac9381570
Create Date: 2025-03-17 04:24:12.659689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fccb9bb0e34d"
down_revision: Union[str, None] = "e89ac9381570"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_filter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("filter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["filter_id"], ["filter.id"], name=op.f("fk_image_filter_filter_id_filter")
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["image.id"], name=op.f("fk_image_filter_image_id_image")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_filter")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image_filter")
    # ### end Alembic commands ###
