"""Create Request Table

Revision ID: 629fc1a85c16
Revises: c16d8d85ee69
Create Date: 2025-03-17 05:00:53.375421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "629fc1a85c16"
down_revision: Union[str, None] = "c16d8d85ee69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "date", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["request_category.id"],
            name=op.f("fk_request_category_id_request_category"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profile.id"], name=op.f("fk_request_profile_id_profile")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request")),
    )
    op.create_index(
        op.f("ix_request_category_id"), "request", ["category_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_category_id"), table_name="request")
    op.drop_table("request")
    # ### end Alembic commands ###
