"""Create Part Table

Revision ID: 2515c308ff2d
Revises: 02bd70877daa
Create Date: 2025-03-17 01:45:06.034043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2515c308ff2d"
down_revision: Union[str, None] = "02bd70877daa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "part",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.SMALLINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part")),
        sa.UniqueConstraint("name", name=op.f("uq_part_name")),
        sa.UniqueConstraint("number", name=op.f("uq_part_number")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("part")
    # ### end Alembic commands ###
