"""Create Character_Chronology Associate_Table

Revision ID: 72c171fe114a
Revises: 16ac842bff65
Create Date: 2025-03-17 01:56:02.904379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72c171fe114a"
down_revision: Union[str, None] = "16ac842bff65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_chronology",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("chronology_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
            name=op.f("fk_character_chronology_character_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["chronology_id"],
            ["chronology.id"],
            name=op.f("fk_character_chronology_chronology_id_chronology"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_chronology")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_chronology")
    # ### end Alembic commands ###
