"""Create Date Table

Revision ID: 02bd70877daa
Revises: ee41bb540052
Create Date: 2025-03-17 01:44:09.019003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02bd70877daa"
down_revision: Union[str, None] = "ee41bb540052"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "date",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.SMALLINT(), nullable=False),
        sa.Column("month", sa.SMALLINT(), nullable=False),
        sa.Column("year", sa.SMALLINT(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_date")),
        sa.UniqueConstraint("day", "month", "year", name="uq_dates_day_month_year"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("date")
    # ### end Alembic commands ###
