"""Create Chronology Table

Revision ID: 52975fa343b8
Revises: 52983860577a
Create Date: 2025-03-17 01:47:07.772433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52975fa343b8"
down_revision: Union[str, None] = "52983860577a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chronology",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=True),
        sa.Column("date_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.id"],
            name=op.f("fk_chronology_chapter_id_chapter"),
        ),
        sa.ForeignKeyConstraint(
            ["date_id"], ["date.id"], name=op.f("fk_chronology_date_id_date")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chronology")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chronology")
    # ### end Alembic commands ###
