"""Create Image Table

Revision ID: e89ac9381570
Revises: cbe6b333e052
Create Date: 2025-03-17 03:36:24.341341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e89ac9381570"
down_revision: Union[str, None] = "cbe6b333e052"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by_AI", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profile.id"], name=op.f("fk_image_profile_id_profile")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image")),
    )
    op.create_index(op.f("ix_image_profile_id"), "image", ["profile_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_image_profile_id"), table_name="image")
    op.drop_table("image")
    # ### end Alembic commands ###
