"""Create Filter Table

Revision ID: 07555b6a718f
Revises: 72c171fe114a
Create Date: 2025-03-17 02:07:11.858203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07555b6a718f"
down_revision: Union[str, None] = "72c171fe114a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filter", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filter")),
        sa.UniqueConstraint("filter", name=op.f("uq_filter_filter")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("filter")
    # ### end Alembic commands ###
